spring.application.name=autosalon-web

# ==== PostgreSQL в Docker ====
spring.datasource.url=jdbc:postgresql://localhost:5433/autosalon
spring.datasource.username=autosalon
spring.datasource.password=autosalon
spring.datasource.driver-class-name=org.postgresql.Driver

# ==== JPA / Hibernate ====
# Создаём/обновляем схему БД по сущностям
spring.jpa.hibernate.ddl-auto=none

# Логируем SQL, чтобы видеть CREATE TABLE и SELECT'ы
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Не тянем вторую БД H2 и т.п.
spring.sql.init.mode=never

# Порт приложения
server.port=8080
